#!/usr/bin/env python3
"""Build admin/preview.css: the site's page styles, scoped so they cannot collide.

Decap applies every registered preview stylesheet to every preview. Loading the
film, book and About styles together therefore put three whole-page stylesheets
in one document, all using bare selectors like `h1`, `body` and `.top`. They
overwrote each other, and the About preview came out centred when the real page
is left-aligned at every width.

So each stylesheet is prefixed with the wrapper class its preview uses, and
whole-document selectors (:root, html, body) are mapped onto that wrapper. The
three then coexist without touching each other.

Rerun after changing any page's CSS:
    python3 tools/build_preview_css.py
"""
import os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STYLES = os.path.join(ROOT, "content", "_styles")
OUT = os.path.join(ROOT, "admin", "preview.css")

# which stylesheet belongs to which preview wrapper
SOURCES = [
    ("the-other-side-of-boredom.css", ".cmt-film"),
    ("_book.css",                     ".cmt-book"),
    ("_about.css",                    ".cmt-about"),
]

# selectors that mean "the whole document" and must become the wrapper itself
# NB: "*" is deliberately NOT here. It is the reset, and it has to keep
# applying to descendants — mapping it onto the wrapper alone would drop
# the margin/padding/box-sizing reset from every element inside.
WHOLE_DOC = {":root", "html", "body", "html, body"}


def scope_selector(sel, wrapper):
    sel = sel.strip()
    if not sel:
        return sel
    if sel in WHOLE_DOC:
        return wrapper
    # "html, body" style groups are split by the caller, so a bare * lands here
    if sel == "*":
        return wrapper + " *"
    if sel.startswith("html") or sel.startswith("body"):
        # e.g. "body.foo .bar" -> ".cmt-x.foo .bar"
        return wrapper + re.sub(r"^(html|body)", "", sel, count=1)
    return wrapper + " " + sel


def scope_block(css, wrapper):
    """Prefix every selector in a block of CSS, recursing through @media."""
    out, i = [], 0
    while i < len(css):
        at = css.find("@", i)
        brace = css.find("{", i)
        if brace == -1:
            out.append(css[i:])
            break
        # an at-rule whose body is itself a block of rules
        if at != -1 and at < brace and re.match(r"@(media|supports|container)", css[at:]):
            head_end = css.index("{", at)
            depth, j = 1, head_end + 1
            while j < len(css) and depth:
                if css[j] == "{": depth += 1
                elif css[j] == "}": depth -= 1
                j += 1
            out.append(css[i:at])
            out.append(css[at:head_end + 1])
            out.append(scope_block(css[head_end + 1:j - 1], wrapper))
            out.append("}")
            i = j
            continue
        # a plain rule
        sel = css[i:brace]
        end = css.find("}", brace)
        if end == -1:
            out.append(css[i:])
            break
        # keep comments and whitespace that sit before the selector
        lead = ""
        m = re.match(r"^(\s*(?:/\*.*?\*/\s*)*)", sel, re.S)
        if m:
            lead, sel = m.group(1), sel[m.end():]
        scoped = ", ".join(scope_selector(s, wrapper) for s in sel.split(",") if s.strip())
        out.append(lead + scoped + css[brace:end + 1])
        i = end + 1
    return "".join(out)


def main():
    parts = ["/* Generated by tools/build_preview_css.py - do not edit.\n"
             "   The site's page styles, each scoped to its preview wrapper so the\n"
             "   three cannot overwrite one another inside Decap's single preview\n"
             "   document. */\n"]
    for name, wrapper in SOURCES:
        css = open(os.path.join(STYLES, name), encoding="utf-8").read()
        parts.append("\n/* ---- %s -> %s ---- */\n" % (name, wrapper))
        parts.append(scope_block(css, wrapper))
    open(OUT, "w", encoding="utf-8").write("".join(parts))
    print("wrote admin/preview.css (%d bytes)" % os.path.getsize(OUT))


if __name__ == "__main__":
    main()
